import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import React from "react";
import useSWR from "swr";
import { Post } from "..";
import styles from "../../styles/Home.module.css";

const fetcher = (url: string) => fetch(url).then((res) => res.json());

const PostPage: React.FC = () => {
  const {
    query: { id },
  } = useRouter();
  const { data, error } = useSWR<Post>(
    `https://jsonplaceholder.typicode.com/posts/${id}`,
    fetcher
  );

  return (
    <div className={styles.container}>
      <Head>
        <title>Post #{id}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {!data ? (
          <>Loading</>
        ) : (
          <>
            <Link href="/">
              <a className="back">&larr; Back to index</a>
            </Link>
            <h1 className={styles.title}>{data.title}</h1>
            <p className={styles.description}>{data.body}</p>
          </>
        )}
      </main>
    </div>
  );
};

export default PostPage;
